### ISSUE TITLE
Looping with function recursion

### ISSUE THREAD

**Issue by Command-Master** [Geekid812/mcfunction-expand#1]
Are you able to make it so you can write something like range(1, 20), and instead of just unrolling it, it will turn it into a recursive function loop?

**Comment by Geekid812** [comment]
That would be a great idea, however creating a recursive loop requires making another function file which the compiler is not able to do at the moment. It could be implemented in the future, but the same result can already be reproduced in the current version, so it's not very high in priorities.

**Comment by Geekid812** [comment]
In fact, I would've started working on this feature right now if I didn't realise one thing: the compiler would need to know how to reference the other function within the datapack. Since the compiler is not currently aware of file structure, it would require a lot of rework and possibly limiting it to only work in datapacks where it can recognise the structure. Unless you have a feasible alternative, I don't think this will be possible for the moment.
